nameSuffix: -dogfooding
namespace: automated-releases

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../bases/automated-release

commonAnnotations:
  managed-by: Tekton

patches:
- path: cronjob-patch.yaml
  target:
    group: batch
    kind: CronJob
    name: scan-release-branches
    version: v1
