resources:
- dashboard-nightly
- pipeline-nightly
- triggers-nightly
- task-loops-nightly
- cel-nightly
- pipelines-in-pipelines-nightly
- add-pr-body-nightly
- add-team-members-nightly
- operator-nightly
