apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://infra.tekton.dev/tekton-releases/pruner/previous/v0.3.3/release.yaml
patches:
  - path: pruner-config.yaml
  - path: deployment-resources-patch.yaml
