apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/tektoncd/pipeline/releases/download/v1.6.0/release.yaml
patches:
- path: config-defaults.yaml
- path: config-observability.yaml
- path: webhook.yaml
- path: controller.yaml
- path: feature-flags.yaml
- path: git-resolver-config.yaml
