apiVersion: v1
kind: ConfigMap
metadata:
  name: config-artifact-bucket
  namespace: tekton-pipelines
data:
  bucket.service.account.field.name: BOTO_CONFIG
  bucket.service.account.secret.key: boto-config
  bucket.service.account.secret.name: tekton-storage
  location: s3://tekton-pipelines
