namespace: default
commonAnnotations:
  managed-by: Tekton

resources:
- images/image-build-trigger.yaml
- org-permissions/peribolos.yaml
- org-permissions/peribolos-trigger.yaml
- release
- cd
- nightly-release