namespace: tekton-nightly
resources:
- serviceaccount.yaml
- bindings.yaml
- eventlistener.yaml
- tasks.yaml
- overlays/dashboard
- overlays/pipeline
- overlays/triggers
- overlays/task-loops
- overlays/cel
- overlays/pipelines-in-pipelines
- overlays/add-pr-body
- overlays/add-pr-body-ci
- overlays/add-team-members
- overlays/operator
- overlays/wait-task
- overlays/pipeline-to-taskrun
- overlays/cloudevents
- overlays/chains
- overlays/pipeline-in-pod
- overlays/pr-commenter
