apiVersion: v1
data:
  config: |
    resources:
    - names:
      - tekton-prow-0
      - tekton-prow-1
      - tekton-prow-2
      - tekton-prow-3
      - tekton-prow-4
      - tekton-prow-5
      - tekton-prow-6
      - tekton-prow-7
      - tekton-prow-8
      - tekton-prow-9
      - tekton-prow-10
      - tekton-prow-11
      - tekton-prow-12
      - tekton-prow-13
      state: dirty
      type: gke-project
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: resources
  namespace: test-pods

