resources:
- tekton-teps-validation.yaml
- tekton-golang-tests.yaml
- tekton-docs-reviews.yaml
- tekton-catalog-catlin-lint.yaml
- tekton-org-validation.yaml
- tekton-python-unit-tests.yaml
- tekton-catalog-diff-task.yaml
- e2e-kind.yaml
- tekton-golang-lint.yaml
- tekton-yamllint.yaml
- tekton-github-tasks-completed.yaml
- tekton-golang-coverage.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
