resources:
- conditions.yaml
- tasks.yaml
- tekton-golang-lint.yaml
- tekton-image-build.yaml
- tekton-kind-label.yaml
- tekton-yamllint.yaml
- tekton-python-test.yaml
- tekton-teps-validation.yaml
- tekton-catlin-lint.yaml
- tekton-golang-tests.yaml