resources:
- alpine-git-nonroot-nightly
- coverage-image-nightly
- hub-nightly
- ko-gcloud-nightly
- ko-nightly
- kubectl-nightly
- openssh-server-nightly
- pipeline-test-runner-nightly
- skopeo-nightly
- tkn-nightly
- yamllint-nightly
- buildx-gcloud-nightly
- teps-community-nightly
- catlin-nightly
- kind-nightly
- go-rest-api-test-nightly
- kind-e2e-nightly
