resources:
- alpine-git-nonroot-nightly
- coverage-image-nightly
- hub-nightly
- ko-gcloud-nightly
- ko-nightly
- koparse-nightly
- kubectl-nightly
- pipeline-test-runner-nightly
- tkn-nightly
- buildx-gcloud-nightly
- teps-community-nightly
- catlin-nightly
- kind-nightly
- go-rest-api-test-nightly
- kind-e2e-nightly
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
